CREATE DATABASE BARBERSHOP;
USE BARBERSHOP;

CREATE TABLE CLIENTES (
ID_CLIENTE INT auto_increment primary KEY,
NOMBRE VARCHAR(25) NOT NULL,
TELEFONO VARCHAR(15),
MAIL VARCHAR(20)
);

RENAME TABLE CLIENTES TO CLIENTE;

CREATE TABLE BARBERO (
ID_BARBERO INT auto_increment primary KEY,
NOMBRE VARCHAR(25) NOT NULL,
TELEFONO VARCHAR(15),
MAIL VARCHAR(20)
);

CREATE TABLE CORTE (
ID_CORTE INT primary KEY,
NOMBRE_CORTE VARCHAR(25) NOT NULL,
PRECIO decimal(10,2) NOT NULL,
DESCRIPCION TEXT
);

CREATE TABLE MEDIOS_DE_PAGO (
ID_MEDIO_DE_PAGO INT primary KEY,
TIPO_DE_PAGO VARCHAR(20)
);

ALTER TABLE MEDIOS_DE_PAGO
MODIFY ID_MEDIO_DE_PAGO INT NOT NULL,
MODIFY TIPO_DE_PAGO VARCHAR(20) NOT NULL;

CREATE TABLE PRODUCTO (
ID_PRODUCTO INT auto_increment primary KEY,
NOMBRE_PRODUCTO VARCHAR(30) NOT NULL,
PRECIO DECIMAL(10,2) NOT NULL,
STOCK INT NOT NULL
);

ALTER TABLE PRODUCTO 
ADD COLUMN ID_PROVEEDOR INT NOT NULL,
ADD FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR);


CREATE TABLE PROVEEDOR (
ID_PROVEEDOR INT AUTO_INCREMENT primary KEY,
NOMBRE VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30),
TELEFONO VARCHAR(17) NOT NULL,
DIRECCION VARCHAR (35)
);

CREATE TABLE RESERVA (
ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
ID_CLIENTE INT NOT NULL,
ID_BARBERO INT NOT NULL,
ID_CORTE INT NOT NULL,
ID_MEDIO_DE_PAGO INT NOT NULL,
FECHA DATE NOT NULL,
HORARIO TIME NOT NULL,
COSTO_TOTAL DECIMAL(8,2) NOT NULL,
ES_ESPONTANEO BOOLEAN DEFAULT FALSE,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
FOREIGN KEY (ID_BARBERO) REFERENCES BARBERO(ID_BARBERO),
FOREIGN KEY (ID_CORTE) REFERENCES CORTE(ID_CORTE),
FOREIGN KEY (ID_MEDIO_DE_PAGO) REFERENCES MEDIOS_DE_PAGO(ID_MEDIO_DE_PAGO)
);

CREATE TABLE CORTE_PRODUCTO (
ID_PRODUCTO INT NOT NULL,
ID_CORTE INT NOT NULL,
CANTIDAD INT NOT NULL,
PRIMARY KEY(ID_PRODUCTO, ID_CORTE),
FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
FOREIGN KEY(ID_CORTE) REFERENCES CORTE(ID_CORTE)
);



